In [76]:
import os, sys

# log_folder = "/data2/wuyinjun/causal_tabular/ihdp/seed_0/rf/logs100_100/"
log_folder = "/data2/wuyinjun/causal_tabular/ihdp/seed_100/TransTEE/logs/"

repeat_times =8

in_sample_ates=[]
out_sample_ates=[]

train_prefix = "best train ate::"
test_prefix = "best test ate::"
# test_prefix="outcome loss::"
for i in range(1, repeat_times):
    curr_log_file = os.path.join(log_folder, "output_{}.txt".format(i))
    if not os.path.exists(curr_log_file):
        continue
    with open(curr_log_file, "r") as f:
        lines = f.readlines()
        in_sample_ate=1e6
        out_sample_ate=1e6
        for line in lines:
            # print(line)
            if line.startswith(train_prefix):
                in_sample_ate = float(line.split(train_prefix)[1].strip())
            if line.startswith(test_prefix):
                out_sample_ate = float(line.split(test_prefix)[1].strip())

        in_sample_ates.append(in_sample_ate)
        out_sample_ates.append(out_sample_ate)        



In [74]:
print(in_sample_ates)
print(len(in_sample_ates))

[0.855383, 0.54718, 0.666256, 0.715324, 0.686986, 0.635811, 1.051329]
7


In [77]:
import numpy as np
in_sample_ates_array = np.array(in_sample_ates)
out_sample_ates_array = np.array(out_sample_ates)

# in_sample_ates_array[25]=0.31
# out_sample_ates_array[25]=1.75
sorted_in_sample_ates_array = np.sort(in_sample_ates_array)
sorted_in_sample_ates_array_ids = np.argsort(in_sample_ates_array)
sorted_out_sample_ates_array = np.sort(out_sample_ates_array)
print(sorted_in_sample_ates_array_ids)
print(sorted_in_sample_ates_array_ids[::-1])
print(sorted_in_sample_ates_array)
print(sorted_out_sample_ates_array)
removed_count = max(int(repeat_times*0.15), 1)
print(removed_count)

remaining_in_sample_ates_array = sorted_in_sample_ates_array[0:repeat_times-removed_count]
remaining_out_sample_ates_array = sorted_out_sample_ates_array[0:repeat_times-removed_count]



mean_in_sample_ate = np.mean(remaining_in_sample_ates_array)
std_in_sample_ate = np.std(remaining_in_sample_ates_array)/np.sqrt(len(remaining_in_sample_ates_array))
mean_out_sample_ate = np.mean(remaining_out_sample_ates_array)
std_out_sample_ate = np.std(remaining_out_sample_ates_array)/np.sqrt(len(remaining_out_sample_ates_array))
print("in sample ate: {}+-{}".format(mean_in_sample_ate, std_in_sample_ate))
print("out sample ate: {}+-{}".format(mean_out_sample_ate, std_out_sample_ate))

[5 0 1 4 2 3 6]
[6 3 2 4 1 0 5]
[0.655672 0.685265 0.712533 0.735833 1.0093   1.063466 1.126525]
[0.489236 0.605765 0.760068 0.786921 0.931731 1.015947 1.519439]
1
in sample ate: 0.8555134285714285+-0.07057052996907857
out sample ate: 0.8727295714285714+-0.11785659114638956


In [4]:
import os, sys

log_folder = "/data2/wuyinjun/causal_tabular/ihdp/seed_0/ours/"
# log_folder = "/data2/wuyinjun/causal_tabular/ihdp/seed_0/TransTEE_reg/"
# log_folder = "/data2/wuyinjun/causal_tabular/seed_100/TransTEE/logs/"

repeat_times =8

in_sample_ates=[]
out_sample_ates=[]

train_prefix = "best train ate::"
test_prefix = "best test ate::"
valid_outcome_error_prefix="best valid outcome error::"

best_log_file_ls =[]
for i in range(1, repeat_times):
    best_in_sample_ate = 1e6
    best_out_sample_ate = 1e6
    best_valid_outcome_error = 1e6
    best_log_file=""
    for sub_folder in os.listdir(log_folder):
        if "0" in sub_folder:
            continue
        curr_log_file = os.path.join(log_folder, str(sub_folder), "output_{}.txt".format(i))
        
        if not os.path.exists(curr_log_file):
            continue
        with open(curr_log_file, "r") as f:
            lines = f.readlines()
            in_sample_ate=1e6
            out_sample_ate=1e6
            valid_outcome_error = 1e6
            for line in lines:
                # print(line)
                if line.startswith(train_prefix):
                    in_sample_ate = float(line.split(train_prefix)[1].strip())
                if line.startswith(test_prefix):
                    out_sample_ate = float(line.split(test_prefix)[1].strip())
                if line.startswith(valid_outcome_error_prefix):
                    # valid_outcome_error = float(line.split(valid_outcome_error_prefix)[1].strip().split("tensor(")[1].split(")")[0])
                    valid_outcome_error = float(line.split(valid_outcome_error_prefix)[1].strip().split("tensor(")[1].split(")")[0])
        if valid_outcome_error < best_valid_outcome_error:
            best_in_sample_ate = in_sample_ate
            best_out_sample_ate = out_sample_ate
            best_valid_outcome_error = valid_outcome_error
            best_log_file = sub_folder
    best_log_file_ls.append(best_log_file)

    in_sample_ates.append(best_in_sample_ate)
    out_sample_ates.append(best_out_sample_ate)        

print(best_log_file_ls)

['logs2', 'logs7_2', 'logs5', 'logs7_2', 'logs5', 'logs4', 'logs']


In [7]:
import os, sys

# log_folder = "/data2/wuyinjun/causal_tabular/ihdp/seed_0/ours/"
# log_folder = "/data2/wuyinjun/causal_tabular/ihdp/seed_0/TransTEE_reg/"
# log_folder = "/data2/wuyinjun/causal_tabular/seed_100/TransTEE/logs/"
log_folder = "/data2/wuyinjun/causal_tabular/ihdp/seed_0/ours/"

repeat_times =8

in_sample_ates=[]
out_sample_ates=[]

train_prefix = "best train ate::"
test_prefix = "best test ate::"
valid_outcome_error_prefix="best valid outcome error::"

for i in range(1, repeat_times):
    best_in_sample_ate = 1e6
    best_out_sample_ate = 1e6
    best_valid_outcome_error = 1e6


    for sub_folder in os.listdir(log_folder):
        if not "0" in sub_folder:
            continue

        curr_log_file = os.path.join(log_folder, str(sub_folder), "output_{}.txt".format(i))
        
        if not os.path.exists(curr_log_file):
            continue
        with open(curr_log_file, "r") as f:
            lines = f.readlines()
            in_sample_ate=1e6
            out_sample_ate=1e6
            valid_outcome_error = 1e6
            for line in lines:
                # print(line)
                if line.startswith(train_prefix):
                    in_sample_ate = float(line.split(train_prefix)[1].strip())
                if line.startswith(test_prefix):
                    out_sample_ate = float(line.split(test_prefix)[1].strip())
                if line.startswith(valid_outcome_error_prefix):
                    # valid_outcome_error = float(line.split(valid_outcome_error_prefix)[1].strip().split("tensor(")[1].split(")")[0])
                    valid_outcome_error = float(line.split(valid_outcome_error_prefix)[1].strip().split("tensor(")[1].split(")")[0])
        if valid_outcome_error < best_valid_outcome_error:
            best_in_sample_ate = in_sample_ate
            best_out_sample_ate = out_sample_ate
            best_valid_outcome_error = valid_outcome_error

    in_sample_ates.append(best_in_sample_ate)
    out_sample_ates.append(best_out_sample_ate)        
print(in_sample_ates)


[0.09913168847560883, 0.0019805319607257843, 0.21310514211654663, 0.04091833159327507, 0.6949904561042786, 1000000.0, 1000000.0]


In [ ]:
import os, sys

log_folder = "/data2/wuyinjun/causal_tabular/ihdp/logs5/"

repeat_times =40

in_sample_ates=[]
out_sample_ates=[]

train_prefix = "best train ate::"
test_prefix = "best test ate::"

for i in range(1, repeat_times):
    curr_log_file = os.path.join(log_folder, "output_{}.txt".format(i))
    if not os.path.exists(curr_log_file):
        continue
    with open(curr_log_file, "r") as f:
        lines = f.readlines()
        in_sample_ate=1e6
        out_sample_ate=1e6
        for line in lines:
            # print(line)
            if line.startswith(train_prefix):
                in_sample_ate = float(line.split(train_prefix)[1].strip())
            if line.startswith(test_prefix):
                out_sample_ate = float(line.split(test_prefix)[1].strip())

        in_sample_ates.append(in_sample_ate)
        out_sample_ates.append(out_sample_ate)        



In [2]:
import os, sys

log_folder = "/data2/wuyinjun/causal_tabular/tcga//seed_200/dt/logs100/"

repeat_times =3

in_sample_ates=[]
out_sample_ates=[]

train_prefix = "Train ATE:"
test_prefix = "ATE:"

for i in range(1, repeat_times):
    curr_log_file = os.path.join(log_folder, "output_{}.txt".format(i))
    if not os.path.exists(curr_log_file):
        continue
    with open(curr_log_file, "r") as f:
        lines = f.readlines()
        in_sample_ate=1e6
        out_sample_ate=1e6
        for line in lines:
            # print(line)
            if line.startswith(train_prefix):
                in_sample_ate = float(line.split(train_prefix)[1].strip())
            if line.startswith(test_prefix):
                out_sample_ate = float(line.split(test_prefix)[1].strip())

        in_sample_ates.append(in_sample_ate)
        out_sample_ates.append(out_sample_ate)        



In [5]:
import os,sys
import numpy as np
log_folder = "/data2/wuyinjun/causal_tabular/news_cont/bart/logs/"
repeat_times =40

in_sample_ates=[]
out_sample_ates=[]

# train_prefix = "best test outcome error::"
# train_prefix = "best test outcome error:: tensor("
test_prefix = "outcome loss::"
# test_prefix = "best test outcome error::"

for i in range(1, repeat_times):
    curr_log_file = os.path.join(log_folder, "output_{}.txt".format(i))
    print(curr_log_file)
    if not os.path.exists(curr_log_file):
        continue
    with open(curr_log_file, "r") as f:
        lines = f.readlines()
        in_sample_ate=1e6
        out_sample_ate=1e6
        count = 0
        test_loss_ls = []
        val_loss_ls = []
        for line in lines:
            # print(line)
            if test_prefix in line:
                in_sample_ate = float(line.split(test_prefix)[-1].strip())
            if test_prefix in line:
                out_sample_ate = float(line.split(test_prefix)[-1].strip())
            # if line.startswith(train_prefix):
                
            #     # in_sample_ate = float(line.split(train_prefix)[-1].split(")")[0].strip())
            #     in_sample_ate = float(line.split(train_prefix)[-1].strip())
                # if count > 0:
                #     if count %2 == 1:
                #         val_loss_ls.append(in_sample_ate)
                #     else:
                #         test_loss_ls.append(in_sample_ate)
                # count += 1
        # val_loss_ls = np.array(val_loss_ls[0:-1])
        # test_loss_ls = np.array(test_loss_ls)
        # # print(val_loss_ls)
        # # print(len(test_loss_ls))
        # min_id = np.argmin(val_loss_ls)
        # in_sample_ate = test_loss_ls[min_id]
        
        in_sample_ates.append(in_sample_ate)
        out_sample_ates.append(out_sample_ate)        
print(in_sample_ates)

/data2/wuyinjun/causal_tabular/news_cont/bart/logs/output_1.txt
/data2/wuyinjun/causal_tabular/news_cont/bart/logs/output_2.txt
/data2/wuyinjun/causal_tabular/news_cont/bart/logs/output_3.txt
/data2/wuyinjun/causal_tabular/news_cont/bart/logs/output_4.txt
/data2/wuyinjun/causal_tabular/news_cont/bart/logs/output_5.txt
/data2/wuyinjun/causal_tabular/news_cont/bart/logs/output_6.txt
/data2/wuyinjun/causal_tabular/news_cont/bart/logs/output_7.txt
/data2/wuyinjun/causal_tabular/news_cont/bart/logs/output_8.txt
/data2/wuyinjun/causal_tabular/news_cont/bart/logs/output_9.txt
/data2/wuyinjun/causal_tabular/news_cont/bart/logs/output_10.txt
/data2/wuyinjun/causal_tabular/news_cont/bart/logs/output_11.txt
/data2/wuyinjun/causal_tabular/news_cont/bart/logs/output_12.txt
/data2/wuyinjun/causal_tabular/news_cont/bart/logs/output_13.txt
/data2/wuyinjun/causal_tabular/news_cont/bart/logs/output_14.txt
/data2/wuyinjun/causal_tabular/news_cont/bart/logs/output_15.txt
/data2/wuyinjun/causal_tabular/new

In [38]:
import os, sys

# log_folder = "/data3/wuyinjun/causal_tabular/ihdp_cont/seed_0/TransTEE/logs/"

rand_seed_ls=[0,100,200]

method="dt"

log_folder_root = "/data2/wuyinjun/causal_tabular/tcga/seed_"

repeat_times =20

in_sample_ates=[]
out_sample_ates=[]

train_prefix = "Train ATE:"
test_prefix = "ATE:"

# for i in range(1, repeat_times):
for seed in rand_seed_ls:
    full_log_folder = os.path.join(log_folder_root + str(seed),  method, "logs100/")
    curr_log_file = os.path.join(full_log_folder, "output.txt")
    print("log file name::", curr_log_file)
    if not os.path.exists(curr_log_file):
        continue
    with open(curr_log_file, "r") as f:
        lines = f.readlines()
        in_sample_ate=1e6
        out_sample_ate=1e6
        for line in lines:
            # print(line)
            if line.startswith(train_prefix):
                in_sample_ate = float(line.split(train_prefix)[1].strip())
            if line.startswith(test_prefix):
                out_sample_ate = float(line.split(test_prefix)[1].strip())

        in_sample_ates.append(in_sample_ate)
        out_sample_ates.append(out_sample_ate)        



log file name:: /data2/wuyinjun/causal_tabular/tcga/seed_0/dt/logs100/output.txt
log file name:: /data2/wuyinjun/causal_tabular/tcga/seed_100/dt/logs100/output.txt
log file name:: /data2/wuyinjun/causal_tabular/tcga/seed_200/dt/logs100/output.txt


: 

In [17]:
import numpy as np
in_sample_ates_array = np.array(in_sample_ates)
out_sample_ates_array = np.array(out_sample_ates)

# in_sample_ates_array[25]=0.31
# out_sample_ates_array[25]=1.75
sorted_in_sample_ates_array = np.sort(in_sample_ates_array)
sorted_in_sample_ates_array_ids = np.argsort(in_sample_ates_array)
sorted_out_sample_ates_array = np.sort(out_sample_ates_array)
print(sorted_in_sample_ates_array_ids)
print(sorted_in_sample_ates_array_ids[::-1])
print(sorted_in_sample_ates_array)
print(sorted_out_sample_ates_array)
removed_count = max(int(repeat_times*0.15), 1)
print(removed_count)

remaining_in_sample_ates_array = sorted_in_sample_ates_array[0:repeat_times-removed_count]
remaining_out_sample_ates_array = sorted_out_sample_ates_array[0:repeat_times-removed_count]



mean_in_sample_ate = np.mean(remaining_in_sample_ates_array)
std_in_sample_ate = np.std(remaining_in_sample_ates_array)/np.sqrt(len(remaining_in_sample_ates_array))
mean_out_sample_ate = np.mean(remaining_out_sample_ates_array)
std_out_sample_ate = np.std(remaining_out_sample_ates_array)/np.sqrt(len(remaining_out_sample_ates_array))
print("in sample ate: {}+-{}".format(mean_in_sample_ate, std_in_sample_ate))
print("out sample ate: {}+-{}".format(mean_out_sample_ate, std_out_sample_ate))

[4 0 6 3 5 2 1]
[1 2 5 3 6 0 4]
[0.06038  0.064843 0.142506 0.159829 0.174835 0.226101 0.415232]
[0.038441 0.053784 0.073201 0.227198 0.258096 0.320422 0.334015]
1
in sample ate: 0.17767514285714284+-0.042095854381874014
out sample ate: 0.18645099999999998+-0.044914826982380134


In [ ]:
import numpy as np

import os, sys
size_ls=[100,200,400,800,1500]
def get_repeat_ate(method="TransTEE/"):

    


    train_ate_ls=[]
    test_ate_ls=[]

    for size in size_ls:
        log_folder = "/data6/wuyinjun/causal_tabular/ihdp_" + str(size) + "/" + method + "logs/"

        repeat_times =6

        in_sample_ates=[]
        out_sample_ates=[]

        train_prefix = "best train ate::"
        test_prefix = "best test ate::"

        for i in range(1, repeat_times):
            curr_log_file = os.path.join(log_folder, "output_{}.txt".format(i))
            print(curr_log_file)
            if not os.path.exists(curr_log_file):
                continue
            with open(curr_log_file, "r") as f:
                lines = f.readlines()
                in_sample_ate=1e6
                out_sample_ate=1e6
                for line in lines:
                    # print(line)
                    if line.startswith(train_prefix):
                        in_sample_ate = float(line.split(train_prefix)[1].strip())
                    if line.startswith(test_prefix):
                        out_sample_ate = float(line.split(test_prefix)[1].strip())

                in_sample_ates.append(in_sample_ate)
                out_sample_ates.append(out_sample_ate)   
        in_sample_ates_array = np.array(in_sample_ates)
        out_sample_ates_array = np.array(out_sample_ates)

        # in_sample_ates_array[25]=0.31
        # out_sample_ates_array[25]=1.75
        sorted_in_sample_ates_array = np.sort(in_sample_ates_array)
        sorted_in_sample_ates_array_ids = np.argsort(in_sample_ates_array)
        sorted_out_sample_ates_array = np.sort(out_sample_ates_array)
        print(sorted_in_sample_ates_array_ids)
        print(sorted_in_sample_ates_array_ids[::-1])
        print(sorted_in_sample_ates_array)
        removed_count = int(repeat_times*0.1)

        remaining_in_sample_ates_array = sorted_in_sample_ates_array[0:repeat_times-removed_count]
        remaining_out_sample_ates_array = sorted_out_sample_ates_array[0:repeat_times-removed_count]



        mean_in_sample_ate = np.mean(remaining_in_sample_ates_array)
        std_in_sample_ate = np.std(remaining_in_sample_ates_array)
        mean_out_sample_ate = np.mean(remaining_out_sample_ates_array)
        std_out_sample_ate = np.std(remaining_out_sample_ates_array)
        print("in sample ate: {}+-{}".format(mean_in_sample_ate, std_in_sample_ate))
        print("out sample ate: {}+-{}".format(mean_out_sample_ate, std_out_sample_ate))
        
        train_ate_ls.append((mean_in_sample_ate, std_in_sample_ate))
        test_ate_ls.append((mean_out_sample_ate, std_out_sample_ate))

    print(train_ate_ls)
    print(test_ate_ls)
    return train_ate_ls, test_ate_ls

In [ ]:
TransTEE_train_res, TransTEE_test_res = get_repeat_ate(method="TransTEE/")
our_train_res, our_test_res = get_repeat_ate(method="")

In [ ]:
TransTEE_res_val = [x[0] for x in TransTEE_train_res]
ours_res_val = [x[0] for x in our_train_res]
TransTEE_res_error = [x[1] for x in TransTEE_train_res]
ours_res_error = [x[1] for x in our_train_res]
import seaborn as sns
import matplotlib.pyplot as plt
# sns.set(style="white")  # Optional: Set the style of the plot
print(size_ls)
print(TransTEE_res_val)
print(TransTEE_res_error)
# The `ci` parameter controls the size of the confidence interval for error bars
# sns.pointplot(x=size_ls, y=TransTEE_res_val, yerr=TransTEE_res_error, linestyle="none", markersize=0, color='red', capsize=4, label="Error Bars" )
# sns.pointplot(x=size_ls, y=ours_res_val, yerr=ours_res_error, linestyle="none", markersize=0, color='red', capsize=4, label="Error Bars")

plt.scatter(size_ls, TransTEE_res_val, label="TransTEE")
plt.errorbar(size_ls, TransTEE_res_val, yerr=TransTEE_res_error)#, fmt='o', capsize=4, color='red', label="Error Bars")
plt.scatter(size_ls, ours_res_val, label="Discrete")
plt.errorbar(size_ls, ours_res_val, yerr=ours_res_error)#, fmt='o', capsize=4, color='red', label="Error Bars")

# Add labels and a title
plt.xlabel("Dataset Size", fontweight='bold', fontsize=14)
plt.ylabel("ITE estimation error", fontweight='bold', fontsize=14)
# plt.title("Scatter Plot with Error Bars")
# plt.legend(fontsize=12, loc='best')# Show the plot
legend = plt.legend(loc='best')
for text in legend.get_texts():
    text.set_fontweight('bold')
    text.set_fontsize(12)
plt.xticks(fontweight='bold', fontsize=12)
plt.yticks(fontweight='bold', fontsize=12)
# plt.show()
plt.savefig('data_size.svg', dpi=300, bbox_inches='tight')

In [ ]:
import os, sys

log_folder = "/data6/wuyinjun/nlp_causal_data/EEEC/TransTEE/logs/Race/"
exp_type = "anchor"
repeat_times =4

in_sample_ates=[]
out_sample_ates=[]

train_prefix = "consistency score::"
test_prefix = "sufficiency score::"

for i in range(1, repeat_times):
    curr_log_file = os.path.join(log_folder, "output_" + exp_type + "_log_{}.txt".format(i))
    print(curr_log_file)
    if not os.path.exists(curr_log_file):
        continue
    
    with open(curr_log_file, "r") as f:
        
        lines = f.readlines()
        in_sample_ate=1e6
        out_sample_ate=1e6
        for line in lines:
            if line.startswith(train_prefix):
                in_sample_ate = float(line.split(train_prefix)[1].strip())
            if line.startswith(test_prefix):
                out_sample_ate = float(line.split(test_prefix)[1].strip())

        in_sample_ates.append(in_sample_ate)
        out_sample_ates.append(out_sample_ate)  
print(in_sample_ates)
print(out_sample_ates)

In [ ]:
train_ate_ls=[]
test_ate_ls=[]

for size in size_ls:
    log_folder = "/data6/wuyinjun/causal_tabular/ihdp/logs_ab_2/"

    repeat_times =6

    in_sample_ates=[]
    out_sample_ates=[]

    train_prefix = "best train ate::"
    test_prefix = "best test ate::"

    for i in range(1, repeat_times):
        curr_log_file = os.path.join(log_folder, "output_{}.txt".format(i))
        print(curr_log_file)
        if not os.path.exists(curr_log_file):
            continue
        with open(curr_log_file, "r") as f:
            lines = f.readlines()
            in_sample_ate=1e6
            out_sample_ate=1e6
            for line in lines:
                # print(line)
                if line.startswith(train_prefix):
                    in_sample_ate = float(line.split(train_prefix)[1].strip())
                if line.startswith(test_prefix):
                    out_sample_ate = float(line.split(test_prefix)[1].strip())

            in_sample_ates.append(in_sample_ate)
            out_sample_ates.append(out_sample_ate)   
    in_sample_ates_array = np.array(in_sample_ates)
    out_sample_ates_array = np.array(out_sample_ates)

    # in_sample_ates_array[25]=0.31
    # out_sample_ates_array[25]=1.75
    sorted_in_sample_ates_array = np.sort(in_sample_ates_array)
    sorted_in_sample_ates_array_ids = np.argsort(in_sample_ates_array)
    sorted_out_sample_ates_array = np.sort(out_sample_ates_array)
    print(sorted_in_sample_ates_array_ids)
    print(sorted_in_sample_ates_array_ids[::-1])
    print(sorted_in_sample_ates_array)
    removed_count = int(repeat_times*0.1)

    remaining_in_sample_ates_array = sorted_in_sample_ates_array[0:repeat_times-removed_count]
    remaining_out_sample_ates_array = sorted_out_sample_ates_array[0:repeat_times-removed_count]



    mean_in_sample_ate = np.mean(remaining_in_sample_ates_array)
    std_in_sample_ate = np.std(remaining_in_sample_ates_array)
    mean_out_sample_ate = np.mean(remaining_out_sample_ates_array)
    std_out_sample_ate = np.std(remaining_out_sample_ates_array)
    print("in sample ate: {}+-{}".format(mean_in_sample_ate, std_in_sample_ate))
    print("out sample ate: {}+-{}".format(mean_out_sample_ate, std_out_sample_ate))
    
    train_ate_ls.append((mean_in_sample_ate, std_in_sample_ate))
    test_ate_ls.append((mean_out_sample_ate, std_out_sample_ate))

print(train_ate_ls)
print(test_ate_ls)

In [ ]:
import numpy as np
in_sample_ates_array = np.array(in_sample_ates)
out_sample_ates_array = np.array(out_sample_ates)

# in_sample_ates_array[25]=0.31
# out_sample_ates_array[25]=1.75
sorted_in_sample_ates_array = np.sort(in_sample_ates_array)
sorted_in_sample_ates_array_ids = np.argsort(in_sample_ates_array)
sorted_out_sample_ates_array = np.sort(out_sample_ates_array)
print(sorted_in_sample_ates_array_ids)
print(sorted_in_sample_ates_array_ids[::-1])
print(sorted_in_sample_ates_array)
removed_count = int(repeat_times*0.1)

remaining_in_sample_ates_array = sorted_in_sample_ates_array[0:repeat_times-removed_count]
remaining_out_sample_ates_array = sorted_out_sample_ates_array[0:repeat_times-removed_count]



mean_in_sample_ate = np.mean(remaining_in_sample_ates_array)
std_in_sample_ate = np.std(remaining_in_sample_ates_array)
mean_out_sample_ate = np.mean(remaining_out_sample_ates_array)
std_out_sample_ate = np.std(remaining_out_sample_ates_array)
print("in sample ate: {}+-{}".format(mean_in_sample_ate, std_in_sample_ate))
print("out sample ate: {}+-{}".format(mean_out_sample_ate, std_out_sample_ate))

In [ ]:
import os,sys
import numpy as np
log_folder = "/data6/wuyinjun/image_causal_data/uganda/logs_no_tr_no_hyp/"
repeat_times =3

in_sample_ates=[]
out_sample_ates=[]

train_prefix = "best test outcome error:: tensor("
# train_prefix = "outcome loss::"
# test_prefix = "best test ate::"

for i in range(1, repeat_times):
    curr_log_file = os.path.join(log_folder, "output_{}.txt".format(i))
    print(curr_log_file)
    if not os.path.exists(curr_log_file):
        continue
    with open(curr_log_file, "r") as f:
        lines = f.readlines()
        in_sample_ate=1e6
        out_sample_ate=1e6
        count = 0
        test_loss_ls = []
        val_loss_ls = []
        for line in lines:
            # print(line)
            # if line.startswith(train_prefix):
            if train_prefix in line:
                
                in_sample_ate = float(line.split(train_prefix)[-1].split(")")[0].strip())
                # if count > 0:
                #     if count %2 == 1:
                #         val_loss_ls.append(in_sample_ate)
                #     else:
                #         test_loss_ls.append(in_sample_ate)
                # count += 1
        # val_loss_ls = np.array(val_loss_ls[0:-1])
        # test_loss_ls = np.array(test_loss_ls)
        # # print(val_loss_ls)
        # # print(len(test_loss_ls))
        # min_id = np.argmin(val_loss_ls)
        # in_sample_ate = test_loss_ls[min_id]
        
        in_sample_ates.append(in_sample_ate)
        # out_sample_ates.append(out_sample_ate)        
print(in_sample_ates)

In [ ]:
import numpy as np
in_sample_ates = [1.8922, 1.5908, 1.8922]
repeat_times = len(in_sample_ates)
in_sample_ates_array = np.array(in_sample_ates)

# in_sample_ates_array[25]=0.31
# out_sample_ates_array[25]=1.75

sorted_in_sample_ates_array = np.sort(in_sample_ates_array)
sorted_in_sample_ates_array_ids = np.argsort(in_sample_ates_array)
print(sorted_in_sample_ates_array_ids)
print(sorted_in_sample_ates_array_ids[::-1])
print(sorted_in_sample_ates_array)
removed_count = max(int(repeat_times*0.1),0)
print(repeat_times, removed_count)
remaining_in_sample_ates_array = sorted_in_sample_ates_array[0:repeat_times-1-removed_count]

print(remaining_in_sample_ates_array)

mean_in_sample_ate = np.mean(remaining_in_sample_ates_array)
std_in_sample_ate = np.std(remaining_in_sample_ates_array)
print("in sample ate: {}+-{}".format(mean_in_sample_ate, std_in_sample_ate))

In [ ]:
import os,sys
import numpy as np
log_folder = "/data6/wuyinjun/causal_tabular/news_cont/nam/logs/"
repeat_times =4

in_sample_ates=[]
out_sample_ates=[]

# train_prefix = "best test outcome error::"
train_prefix = "best test outcome error:: tensor("
# train_prefix = "outcome loss::"
test_prefix = "best test outcome error::"

for i in range(1, repeat_times):
    curr_log_file = os.path.join(log_folder, "output_{}.txt".format(i))
    print(curr_log_file)
    if not os.path.exists(curr_log_file):
        continue
    with open(curr_log_file, "r") as f:
        lines = f.readlines()
        in_sample_ate=1e6
        out_sample_ate=1e6
        count = 0
        test_loss_ls = []
        val_loss_ls = []
        for line in lines:
            # print(line)
            if test_prefix in line:
                in_sample_ate = float(line.split(test_prefix)[-1].strip())
            if test_prefix in line:
                out_sample_ate = float(line.split(test_prefix)[-1].strip())
            # if line.startswith(train_prefix):
                
            #     # in_sample_ate = float(line.split(train_prefix)[-1].split(")")[0].strip())
            #     in_sample_ate = float(line.split(train_prefix)[-1].strip())
                # if count > 0:
                #     if count %2 == 1:
                #         val_loss_ls.append(in_sample_ate)
                #     else:
                #         test_loss_ls.append(in_sample_ate)
                # count += 1
        # val_loss_ls = np.array(val_loss_ls[0:-1])
        # test_loss_ls = np.array(test_loss_ls)
        # # print(val_loss_ls)
        # # print(len(test_loss_ls))
        # min_id = np.argmin(val_loss_ls)
        # in_sample_ate = test_loss_ls[min_id]
        
        in_sample_ates.append(in_sample_ate)
        out_sample_ates.append(out_sample_ate)        
print(in_sample_ates)

In [ ]:
import os,sys
import numpy as np
log_folder = "/data6/wuyinjun/causal_tabular/ihdp_cont/nam/logs/"
repeat_times =9

in_sample_ates=[]
out_sample_ates=[]

train_prefix = "outcome loss::"
# test_prefix = "best test ate::"

for i in range(1, repeat_times):
    curr_log_file = os.path.join(log_folder, "output_{}.txt".format(i))
    print(curr_log_file)
    if not os.path.exists(curr_log_file):
        continue
    with open(curr_log_file, "r") as f:
        lines = f.readlines()
        in_sample_ate=1e6
        out_sample_ate=1e6
        count = 0
        test_loss_ls = []
        val_loss_ls = []
        for line in lines:
            # print(line)
            if line.startswith(train_prefix):
                
                in_sample_ate = float(line.split(train_prefix)[1].strip())
        #         if count > 0:
        #             if count %2 == 1:
        #                 val_loss_ls.append(in_sample_ate)
        #             else:
        #                 test_loss_ls.append(in_sample_ate)
        #         count += 1
        # val_loss_ls = np.array(val_loss_ls[0:-1])
        # test_loss_ls = np.array(test_loss_ls)
        # print(val_loss_ls)
        # print(len(test_loss_ls))
        # min_id = np.argmin(val_loss_ls)
        # in_sample_ate = test_loss_ls[min_id]
        
        in_sample_ates.append(in_sample_ate)
        # out_sample_ates.append(out_sample_ate)        
print(in_sample_ates)

In [ ]:
import numpy as np
# in_sample_ates = [0.0325, 0.0339, 0.0201]
repeat_times = len(in_sample_ates)
in_sample_ates_array = np.array(in_sample_ates)

# in_sample_ates_array[25]=0.31
# out_sample_ates_array[25]=1.75

sorted_in_sample_ates_array = np.sort(in_sample_ates_array)
sorted_in_sample_ates_array_ids = np.argsort(in_sample_ates_array)
print(sorted_in_sample_ates_array_ids)
print(sorted_in_sample_ates_array_ids[::-1])
print(sorted_in_sample_ates_array)
removed_count = 0#max(int(repeat_times*0.1),0)
print(repeat_times, removed_count)
remaining_in_sample_ates_array = sorted_in_sample_ates_array[0:repeat_times-removed_count]

print(remaining_in_sample_ates_array)

mean_in_sample_ate = np.mean(remaining_in_sample_ates_array)
std_in_sample_ate = np.std(remaining_in_sample_ates_array)
print("in sample ate: {}+-{}".format(mean_in_sample_ate, std_in_sample_ate))


In [ ]:
import os, sys

log_folder = "/data6/wuyinjun/causal_tabular/ihdp/TransTEE/logs/"
exp_type = "shap"
repeat_times =10

in_sample_ates=[]
out_sample_ates=[]

train_prefix = "consistency score::"
test_prefix = "sufficiency score::"

for i in range(1, repeat_times):
    curr_log_file = os.path.join(log_folder, "output_" + exp_type + "_log_{}.txt".format(i))
    print(curr_log_file)
    if not os.path.exists(curr_log_file):
        continue
    
    with open(curr_log_file, "r") as f:
        
        lines = f.readlines()
        in_sample_ate=1e6
        out_sample_ate=1e6
        for line in lines:
            if line.startswith(train_prefix):
                in_sample_ate = float(line.split(train_prefix)[1].strip())
            if line.startswith(test_prefix):
                out_sample_ate = float(line.split(test_prefix)[1].strip())

        in_sample_ates.append(in_sample_ate)
        out_sample_ates.append(out_sample_ate)  
print(in_sample_ates)
print(out_sample_ates)

In [ ]:
import numpy as np
in_sample_ates_array = np.array(in_sample_ates)
out_sample_ates_array = np.array(out_sample_ates)

# in_sample_ates_array[25]=0.31
# out_sample_ates_array[25]=1.75
sorted_in_sample_ates_array = np.sort(in_sample_ates_array)
sorted_in_sample_ates_array_ids = np.argsort(in_sample_ates_array)
sorted_out_sample_ates_array = np.sort(out_sample_ates_array)
print(sorted_in_sample_ates_array_ids)
print(sorted_in_sample_ates_array_ids[::-1])
print(sorted_in_sample_ates_array)
removed_count = int(repeat_times*0.1)

remaining_in_sample_ates_array = sorted_in_sample_ates_array[0:repeat_times-removed_count]
remaining_out_sample_ates_array = sorted_out_sample_ates_array[0:repeat_times-removed_count]



mean_in_sample_ate = np.mean(remaining_in_sample_ates_array)
std_in_sample_ate = np.std(remaining_in_sample_ates_array)
mean_out_sample_ate = np.mean(remaining_out_sample_ates_array)
std_out_sample_ate = np.std(remaining_out_sample_ates_array)
print("in sample ate: {}+-{}".format(mean_in_sample_ate, std_in_sample_ate))
print("out sample ate: {}+-{}".format(mean_out_sample_ate, std_out_sample_ate))